name: Deploy to Firebase

on:
  push:
    branches: [ Live, master ]
  pull_request:
    branches: [ Live, master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          iftaway-frontend/package-lock.json
          functions/package-lock.json
          
    - name: Install frontend dependencies
      run: |
        cd iftaway-frontend
        npm ci
        
    - name: Install functions dependencies
      run: |
        cd functions
        npm ci
        
    - name: Build frontend
      env:
        VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
      run: |
        cd iftaway-frontend
        npm run build
        
    - name: Build functions
      run: |
        cd functions
        npm run build
        
    - name: Deploy to Firebase
      if: github.ref == 'refs/heads/Live' || github.ref == 'refs/heads/master'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IFTAWAY }}'
        projectId: iftaway
        channelId: live
